DROP TABLE IF EXISTS venuePizza;
DROP TABLE IF EXISTS tastes;
DROP TABLE IF EXISTS pizzas;
DROP TABLE IF EXISTS venues;

CREATE TABLE tastes (
	taste_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	cheesiness INTEGER NOT NULL,
	flavor INTEGER NOT NULL,
	sauciness INTEGER NOT NULL,
	saltiness INTEGER NOT NULL,
	charness INTEGER NOT NULL
	created_at TIMESTAMP NOT NULL
);

CREATE TABLE pizzas (
	pizza_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR ( 50 ) NOT NULL,
	category VARCHAR ( 50 ) NOT NULL,
	description TEXT NOT NULL,
	taste_id INT REFERENCES taste(taste_id) ON DELETE CASCADE,
	updated_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL
);

CREATE TABLE venues (
	venue_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR ( 50 ) NOT NULL,
	lat DOUBLE PRECISION,
	lon DOUBLE PRECISION,
	address VARCHAR ( 80 )
);

CREATE TABLE venuePizza (
	venue_pizza_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	pizza_id INT REFERENCES pizzas(pizza_id) ON DELETE CASCADE,
	venue_id INT REFERENCES venue(venue_id) ON DELETE CASCADE
);
